# Generated by Django 4.1.4 on 2023-01-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_rename_review_user_review_reviewuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewuser',
            new_name='review_user',
        ),
    ]
